name: CI Pipeline

on: 
  pull_request:
    branches:
      [devel, stage, prod]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/environments/${{ github.event.pull_request.base.ref }}

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Enforce branching strategy
        if: github.event_name == 'pull_request'
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "stage" &&  "${{ github.event.pull_request.head.ref }}" != "dev"]]
            echo "Merge into stage can only be done from devel"
            exit 1
          fi
          if [[ "${{ github.event.pull_request.base.ref }}" == "prod" &&  "${{ github.event.pull_request.head.ref }}" != "stage"]]
            echo "Merge into prod can only be done from stage"
            exit 1
          fi

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plam
        run: terraform plan 